### PR TITLE
Use css-element-queries resize sensor instead of `window on resize`

### PR DESCRIPTION
**Pull request by jhen0409**
Sorry, I overlooked element resize (e.g. react-dock right mode) at #20, so I used [css-element-queries](https://github.com/marcj/css-element-queries) to solve it, not listen window resize.

### CODE REVIEW

**Comment by calesce** [comment]
Awesome! I hadn't considered that either, since I wouldn't recommend right/left mode, at least for right now :wink:

Only nitpick is can you use an ES6 import and put it at the top of the file?

**Comment by jhen0409** [comment]
@calesce It have a reason is [css-element-queries/src/ResizeSensor](https://github.com/marcj/css-element-queries/blob/master/src/ResizeSensor.js#L9) uses `window` at the beginning.

**Comment by calesce** [comment]
Ok, well I guess trying to server render will break that, so in that case that makes sense. I don't like mixing ES6/CommonJS in general, but there's always exceptions :stuck_out_tongue: 

Thanks again!

**Comment by calesce** [comment]
Hey by the way, would you mind if I add you as a contributor? Sometimes I don't get to issues/PRs quickly enough, and I appreciate the recent help.

**Comment by jhen0409** [comment]
Ok, I will keep to help. :D

**Comment by jhen0409** [comment]
@calesce Could you please publish v1.0.3?

**Comment by calesce** [comment]
Whoops, thanks for the reminder! Also, added you as a collaborator on NPM.

**Pull request merged**
